# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ee699c5cd0c370178c7d46864bc3a4bd020471ba17bccefbb2e0f9ef881a3fd2ae0e2dc5bce9ae56c3ced147acef10e44aa5c5fab83d053fe19cd07af4c18c

test:
  secret_key_base: 2cee97dabd6eac2f3f07068c3c0c77f10de58531cd8cedb12b0547dd5967fb03399b4d4f7ae6f447f33beb5c56c14b0d33b65dde7b2cfc1c53b7e5a847a58ca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
